name: Create Privōx Release

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Release version (e.g., v1.0.0)'
        required: true
        default: 'v1.0.0'
      release_name:
        description: 'Release name (e.g., Privōx Genesis Release)'
        required: true
        default: 'Privōx Genesis Release'

jobs:
  build-and-release:
    runs-on: ubuntu-20.04
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive
        
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          cmake \
          libboost-all-dev \
          libssl-dev \
          libzmq3-dev \
          libunbound-dev \
          libsodium-dev \
          libunwind8-dev \
          liblzma-dev \
          libreadline6-dev \
          libldns-dev \
          libexpat1-dev \
          libpgm-dev \
          libhidapi-dev \
          libusb-1.0-0-dev \
          libprotobuf-dev \
          protobuf-compiler \
          libudev-dev \
          libgcrypt20-dev \
          pkg-config
          
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      
    - name: Build Privōx
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=Release ..
        make -j$(nproc)
        
    - name: Test binaries
      run: |
        cd build
        echo "Testing Privōx daemon version:"
        ./bin/privoxd --version
        echo "Testing wallet CLI:"
        ./bin/privox-wallet-cli --version || echo "Wallet CLI ready"
        
    - name: Create release packages
      run: |
        # Create daemon-only package
        mkdir -p privox-daemon-linux-x64
        cp build/bin/privoxd privox-daemon-linux-x64/
        cp build/bin/privox-wallet-cli privox-daemon-linux-x64/
        cp build/bin/privox-wallet-rpc privox-daemon-linux-x64/
        cp build/bin/privox-blockchain-* privox-daemon-linux-x64/ 2>/dev/null || true
        cp README.md privox-daemon-linux-x64/
        cp LAUNCH_COMMANDS.md privox-daemon-linux-x64/
        cp DEPLOYMENT_READY.md privox-daemon-linux-x64/
        
        # Create start scripts
        cat > privox-daemon-linux-x64/start-mainnet.sh << 'EOF'
#!/bin/bash
echo "🚀 Starting Privōx Mainnet Daemon"
echo "📡 RPC Port: 18236 | P2P Port: 17236"
echo "🔗 Network: Mainnet (addresses start with 'P')"
echo "💰 Genesis: 10M PVX premine"
echo "⏹️  Press Ctrl+C to stop"
echo ""
./privoxd --rpc-bind-port 18236 --p2p-bind-port 17236 --confirm-external-bind
EOF
        
        cat > privox-daemon-linux-x64/start-testnet.sh << 'EOF'
#!/bin/bash
echo "🧪 Starting Privōx Testnet Daemon"
echo "📡 RPC Port: 28236 | P2P Port: 27236"
echo "🔗 Network: Testnet (addresses start with 'T')"
echo "💰 Genesis: 10M PVX premine"
echo "⏹️  Press Ctrl+C to stop"
echo ""
./privoxd --testnet --rpc-bind-port 28236 --p2p-bind-port 27236 --confirm-external-bind
EOF
        
        cat > privox-daemon-linux-x64/create-wallet.sh << 'EOF'
#!/bin/bash
echo "💼 Creating new Privōx wallet"
echo "Follow the prompts to create your wallet..."
echo ""
./privox-wallet-cli --generate-new-wallet mywallet.keys
EOF
        
        chmod +x privox-daemon-linux-x64/*.sh
        
        # Create README for the package
        cat > privox-daemon-linux-x64/README-PACKAGE.md << 'EOF'
# Privōx Linux Package

## 🚀 Quick Start

### Start Mainnet (Production):
```bash
./start-mainnet.sh
```

### Start Testnet (Testing):
```bash
./start-testnet.sh
```

### Create Wallet:
```bash
./create-wallet.sh
```

## 📁 Included Files
- `privoxd` - Main daemon
- `privox-wallet-cli` - Command-line wallet
- `privox-wallet-rpc` - RPC wallet server
- `privox-blockchain-*` - Blockchain utilities
- `start-mainnet.sh` - Launch mainnet daemon
- `start-testnet.sh` - Launch testnet daemon
- `create-wallet.sh` - Create new wallet

## 🔧 Network Info
- **Mainnet**: P2P 17236, RPC 18236, addresses start with "P"
- **Testnet**: P2P 27236, RPC 28236, addresses start with "T"

## 💰 Economics
- Total Supply: 500M PVX
- Decimals: 6
- Block Reward: 120 PVX
- Premine: 10M PVX

Ready to launch! 🎉
EOF
        
        tar -czf privox-daemon-linux-x64.tar.gz privox-daemon-linux-x64/
        
        # Create checksums
        sha256sum privox-daemon-linux-x64.tar.gz > checksums.txt
        
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.event.inputs.release_version }}
        release_name: ${{ github.event.inputs.release_name }}
        body: |
          # ${{ github.event.inputs.release_name }}
          
          ## 🎉 Privōx Cryptocurrency - Ready for Launch!
          
          Complete implementation of Privōx (PVX) cryptocurrency with full privacy features.
          
          ### ✅ What's Included
          - **privoxd** - Main blockchain daemon
          - **privox-wallet-cli** - Command-line wallet
          - **privox-wallet-rpc** - RPC wallet server  
          - **Blockchain utilities** - Import/export and analysis tools
          - **Launch scripts** - Easy start for mainnet and testnet
          
          ### 🚀 Quick Start
          
          1. **Download**: `privox-daemon-linux-x64.tar.gz`
          2. **Extract**: `tar -xzf privox-daemon-linux-x64.tar.gz`
          3. **Launch**: `cd privox-daemon-linux-x64 && ./start-mainnet.sh`
          
          ### 🔧 Network Configuration
          
          | Network | P2P Port | RPC Port | Address Prefix | Genesis Block |
          |---------|----------|----------|----------------|---------------|
          | Mainnet | 17236 | 18236 | P | 12376c5a... |
          | Testnet | 27236 | 28236 | T | 47aea06c... |
          
          ### 💰 Economic Parameters
          - **Total Supply**: 500,000,000 PVX
          - **Decimals**: 6 (1 PVX = 1,000,000 atomic units)
          - **Genesis Premine**: 10,000,000 PVX (2% of supply)
          - **Block Reward**: 120 PVX (halving every ~4 years)
          - **Block Time**: 2 minutes
          - **Tail Emission**: 1 PVX per block after 490M PVX emitted
          
          ### 🔒 Privacy Features
          - **Ring Signatures**: Hide transaction sender
          - **Stealth Addresses**: Hide transaction receiver  
          - **RingCT**: Hide transaction amounts
          - **Complete Anonymity**: Full Monero privacy implementation
          
          ### 🖥️ System Requirements
          - **OS**: Linux (Ubuntu 18.04+ recommended)
          - **RAM**: 2GB minimum, 4GB recommended
          - **Storage**: 50GB+ for full blockchain
          - **Network**: Stable internet connection
          
          ### 🆘 Support
          - Check `LAUNCH_COMMANDS.md` for detailed instructions
          - Review `DEPLOYMENT_READY.md` for deployment guide
          - Open firewall ports: `sudo ufw allow 17236/tcp && sudo ufw allow 18236/tcp`
          
          **Status: Production Ready!** 🚀
          
          ---
          
          **Verification**: Check SHA256 checksums before use
        draft: false
        prerelease: false
        
    - name: Upload daemon package
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./privox-daemon-linux-x64.tar.gz
        asset_name: privox-daemon-linux-x64.tar.gz
        asset_content_type: application/gzip
        
    - name: Upload checksums
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./checksums.txt
        asset_name: checksums.txt
        asset_content_type: text/plain